[colors.primary]
background = "#1a2238"
foreground = "#afb6c5"

[colors.cursor]
text = "#1a2238"
cursor = "#d4be68"

[colors.vi_mode_cursor]
text = "#1a2238"
cursor = "#d4be68"

[colors.search.matches]
foreground = "#1a2238"
background = "#afb6c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#80889c"
background = "#afb6c5"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#182133"
red = "#cf9276"
green = "#5f99a4"
yellow = "#d4be68"
blue = "#7f8fe0"
magenta = "#9586cf"
cyan = "#77b7c8"
white = "#afb6c5"

[colors.bright]
black = "#80889c"
red = "#e2b099"
green = "#7db9c4"
yellow = "#e4d294"
blue = "#a8b4f2"
magenta = "#b4a7e4"
cyan = "#9dd1df"
white = "#dde2eb"

[colors.dim]
black = "#80889c"
red = "#e2b099"
green = "#7db9c4"
yellow = "#e4d294"
blue = "#a8b4f2"
magenta = "#b4a7e4"
cyan = "#9dd1df"
white = "#dde2eb"
