accent = "#d4be68"
cursor = "#d4be68"
foreground = "#afb6c5"
background = "#1a2238"
selection_foreground = "#1a2238"
selection_background = "#d4be68"


color0 = "#1a2238"
color1 = "#cf9276"
color2 = "#5f99a4"
color3 = "#d4be68"
color4 = "#7f8fe0"
color5 = "#9586cf"
color6 = "#77b7c8"
color7 = "#afb6c5"
color8 = "#58647f"
color9 = "#e2b099"
color10 = "#7db9c4"
color11 = "#e4d294"
color12 = "#a8b4f2"
color13 = "#b4a7e4"
color14 = "#9dd1df"
color15 = "#e3e7ef"
