accent = "#6874bb"
cursor = "#cbcbcb"
foreground = "#cbcbcb"
background = "#1a2238"
selection_foreground = "#cbcbcb"
selection_background = "#6874bb"

color0 = "#1a2238"
color1 = "#BD8767"
color2 = "#184c55"
color3 = "#b9a246"
color4 = "#6874bb"
color5 = "#434773"
color6 = "#649FB6"
color7 = "#909090"
color8 = "#48465a"
color9 = "#dbb9a5"
color10 = "#238193"
color11 = "#baaf80"
color12 = "#e6e7f4"
color13 = "#a1a6cb"
color14 = "#a0c7d6"
color15 = "#cbcbcb"
