# foot.ini
# By OldJobobo (https://github.com/OldJobobo)
#

[main]
font=monospace:size=11
pad=14x14 center

[colors-dark]
alpha = 0.90

foreground=afb6c5
background=1a2238

cursor=1a2238 d4be68

regular0=1a2238
regular1=cf9276
regular2=5f99a4
regular3=d4be68
regular4=7f8fe0
regular5=9586cf
regular6=77b7c8
regular7=afb6c5

bright0=58647f
bright1=e2b099
bright2=7db9c4
bright3=e4d294
bright4=a8b4f2
bright5=b4a7e4
bright6=9dd1df
bright7=e3e7ef

selection-foreground=1a2238
selection-background=d4be68
