# Background and foreground colors
background = #1a2238
foreground = #afb6c5

# Standard colors
palette = 0=#182133
palette = 1=#cf9276
palette = 2=#5f99a4
palette = 3=#d4be68
palette = 4=#7f8fe0
palette = 5=#9586cf
palette = 6=#77b7c8
palette = 7=#afb6c5

# Bright colors
palette = 8=#80889c
palette = 9=#e2b099
palette = 10=#7db9c4
palette = 11=#e4d294
palette = 12=#a8b4f2
palette = 13=#b4a7e4
palette = 14=#9dd1df
palette = 15=#dde2eb
