$color = rgba(26, 34, 56, 1)
$inner_color = rgba(26, 34, 56, 0.66)
$outer_color = rgba(67, 71, 115, 1)
$font_color = rgba(203, 203, 203, 1)
$placeholder_color = rgba(203, 203, 203, 0.7)
$check_color = rgba(100, 159, 182, 1)
