-- Generated by scripts/hypr2lua.
-- Source: omarchy-the-loop-theme/hyprland.conf

local activeBorderColor = {
  colors = { "rgb(d4be68)", "rgb(e4d294)" },
  angle = 45,
}
local inactiveBorderColor = "rgba(80889c88)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    border_size = 2,
    gaps_in = 4,
    gaps_out = 8,
    resize_on_border = true,
  },
  decoration = {
    rounding = 8,
    shadow = {
      enabled = true,
      range = 25,
      render_power = 3,
      color = "rgba(d4be6866)",
      color_inactive = "rgba(00000059)",
    },
    blur = {
      enabled = true,
      size = 4,
      passes = 2,
    },
  },
  group = {
    col = {
      border_active = activeBorderColor,
    },
  },
})
