background            #171624
foreground            #cbcbcb

# black
color0  #171624
color8  #48465a

# red
color1  #BD8767
color9  #dbb9a5

# green
color2  #184c55
color10 #238193

# yellow
color3  #b9a246
color11 #baaf80

# blue
color4  #6874bb
color12 #e6e7f4

# magenta
color5  #434773
color13 #a1a6cb

#cyan
color6  #649FB6
color14 #a0c7d6

#white
color7  #909090
color15 #cbcbcb


