background            #1a2238
foreground            #afb6c5
background_opacity    0.90

# black
color0  #182133
color8  #80889c

# red
color1  #cf9276
color9  #e2b099

# green
color2  #5f99a4
color10 #7db9c4

# yellow
color3  #d4be68
color11 #e4d294

# blue
color4  #7f8fe0
color12 #a8b4f2

# magenta
color5  #9586cf
color13 #b4a7e4

#cyan
color6  #77b7c8
color14 #9dd1df

#white
color7  #afb6c5
color15 #dde2eb
